require "user.options"
require "user.keymaps"
require "user.plugins"
require "user.nvim-tree"
require "user.lualine"
require "user.treesitter"
require "user.telescope"
require "user.autopairs"
require "user.blankline"
require "user.tabby"

require "user.lsp-zero"
require "user.dap"
